
package br.com.fiap3espg.stubClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SubtractionService", targetNamespace = "http://service.fiap3espg.com.br/", wsdlLocation = "http://localhost:8080/calculadora/subtracao?wsdl")
public class SubtractionService
    extends Service
{

    private static final URL SUBTRACTIONSERVICE_WSDL_LOCATION;
    private static final WebServiceException SUBTRACTIONSERVICE_EXCEPTION;
    private static final QName SUBTRACTIONSERVICE_QNAME = new QName("http://service.fiap3espg.com.br/", "SubtractionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/calculadora/subtracao?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUBTRACTIONSERVICE_WSDL_LOCATION = url;
        SUBTRACTIONSERVICE_EXCEPTION = e;
    }

    public SubtractionService() {
        super(__getWsdlLocation(), SUBTRACTIONSERVICE_QNAME);
    }

    public SubtractionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBTRACTIONSERVICE_QNAME, features);
    }

    public SubtractionService(URL wsdlLocation) {
        super(wsdlLocation, SUBTRACTIONSERVICE_QNAME);
    }

    public SubtractionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBTRACTIONSERVICE_QNAME, features);
    }

    public SubtractionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubtractionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Operation
     */
    @WebEndpoint(name = "SubtractionPort")
    public Operation getSubtractionPort() {
        return super.getPort(new QName("http://service.fiap3espg.com.br/", "SubtractionPort"), Operation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Operation
     */
    @WebEndpoint(name = "SubtractionPort")
    public Operation getSubtractionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.fiap3espg.com.br/", "SubtractionPort"), Operation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBTRACTIONSERVICE_EXCEPTION!= null) {
            throw SUBTRACTIONSERVICE_EXCEPTION;
        }
        return SUBTRACTIONSERVICE_WSDL_LOCATION;
    }

}
