
package br.com.fiap3espg.stubClasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SumService", targetNamespace = "http://service.fiap3espg.com.br/", wsdlLocation = "http://localhost:8080/calculadora/soma?wsdl")
public class SumService
    extends Service
{

    private static final URL SUMSERVICE_WSDL_LOCATION;
    private static final WebServiceException SUMSERVICE_EXCEPTION;
    private static final QName SUMSERVICE_QNAME = new QName("http://service.fiap3espg.com.br/", "SumService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/calculadora/soma?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUMSERVICE_WSDL_LOCATION = url;
        SUMSERVICE_EXCEPTION = e;
    }

    public SumService() {
        super(__getWsdlLocation(), SUMSERVICE_QNAME);
    }

    public SumService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUMSERVICE_QNAME, features);
    }

    public SumService(URL wsdlLocation) {
        super(wsdlLocation, SUMSERVICE_QNAME);
    }

    public SumService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUMSERVICE_QNAME, features);
    }

    public SumService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SumService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Operation
     */
    @WebEndpoint(name = "SumPort")
    public Operation getSumPort() {
        return super.getPort(new QName("http://service.fiap3espg.com.br/", "SumPort"), Operation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Operation
     */
    @WebEndpoint(name = "SumPort")
    public Operation getSumPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.fiap3espg.com.br/", "SumPort"), Operation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUMSERVICE_EXCEPTION!= null) {
            throw SUMSERVICE_EXCEPTION;
        }
        return SUMSERVICE_WSDL_LOCATION;
    }

}
